### ISSUE TITLE
some admin buttons not working

### ISSUE THREAD

**Issue by NetroSK** [mmmaly/OpenSourceBikeShare#81]
button "Last usage" is not working, from desktop nor from mobile device.

**Comment by nekromoff** [comment]
fixed i commit #b4614146717d18cb200651424d2697801eecff90

**Comment by NetroSK** [comment]
doesn't seem to help... still not working in Firefox and Chrome (desktop) and Chrome (Android)

**Comment by nekromoff** [comment]
it works, but pushing to github does not automatically propagate changes to
(any) local installation
